export const COUNTRIES = [
    { name: "Afghanistan", chinese: "阿富汗" },
    { name: "Albania", chinese: "阿尔巴尼亚" },
    { name: "Algeria", chinese: "阿尔及利亚" },
    { name: "Andorra", chinese: "安道尔" },
    { name: "Angola", chinese: "安哥拉" },
    { name: "Antigua and Barbuda", chinese: "安提瓜和巴布达" },
    { name: "Argentina", chinese: "阿根廷" },
    { name: "Armenia", chinese: "亚美尼亚" },
    { name: "Australia", chinese: "澳大利亚" },
    { name: "Austria", chinese: "奥地利" },
    { name: "Azerbaijan", chinese: "阿塞拜疆" },
    { name: "Bahamas", chinese: "巴哈马" },
    { name: "Bahrain", chinese: "巴林" },
    { name: "Bangladesh", chinese: "孟加拉国" },
    { name: "Barbados", chinese: "巴巴多斯" },
    { name: "Belarus", chinese: "白俄罗斯" },
    { name: "Belgium", chinese: "比利时" },
    { name: "Belize", chinese: "伯利兹" },
    { name: "Benin", chinese: "贝宁" },
    { name: "Bhutan", chinese: "不丹" },
    { name: "Bolivia", chinese: "玻利维亚" },
    { name: "Bosnia and Herzegovina", chinese: "波斯尼亚和黑塞哥维那" },
    { name: "Botswana", chinese: "博茨瓦纳" },
    { name: "Brazil", chinese: "巴西" },
    { name: "Brunei", chinese: "文莱" },
    { name: "Bulgaria", chinese: "保加利亚" },
    { name: "Burkina Faso", chinese: "布基纳法索" },
    { name: "Burundi", chinese: "布隆迪" },
    { name: "Cabo Verde", chinese: "佛得角" },
    { name: "Cambodia", chinese: "柬埔寨" },
    { name: "Cameroon", chinese: "喀麦隆" },
    { name: "Canada", chinese: "加拿大" },
    { name: "Central African Republic", chinese: "中非共和国" },
    { name: "Chad", chinese: "乍得" },
    { name: "Chile", chinese: "智利" },
    { name: "China", chinese: "中国" },
    { name: "Colombia", chinese: "哥伦比亚" },
    { name: "Comoros", chinese: "科摩罗" },
    { name: "Congo (Congo-Brazzaville)", chinese: "刚果（布）" },
    { name: "Costa Rica", chinese: "哥斯达黎加" },
    { name: "Croatia", chinese: "克罗地亚" },
    { name: "Cuba", chinese: "古巴" },
    { name: "Cyprus", chinese: "塞浦路斯" },
    { name: "Czechia (Czech Republic)", chinese: "捷克" },
    { name: "Democratic Republic of the Congo", chinese: "刚果（金）" },
    { name: "Denmark", chinese: "丹麦" },
    { name: "Djibouti", chinese: "吉布提" },
    { name: "Dominica", chinese: "多米尼克" },
    { name: "Dominican Republic", chinese: "多米尼加共和国" },
    { name: "Ecuador", chinese: "厄瓜多尔" },
    { name: "Egypt", chinese: "埃及" },
    { name: "El Salvador", chinese: "萨尔瓦多" },
    { name: "Equatorial Guinea", chinese: "赤道几内亚" },
    { name: "Eritrea", chinese: "厄立特里亚" },
    { name: "Estonia", chinese: "爱沙尼亚" },
    { name: "Eswatini", chinese: "斯威士兰" },
    { name: "Ethiopia", chinese: "埃塞俄比亚" },
    { name: "Fiji", chinese: "斐济" },
    { name: "Finland", chinese: "芬兰" },
    { name: "France", chinese: "法国" },
    { name: "Gabon", chinese: "加蓬" },
    { name: "Gambia", chinese: "冈比亚" },
    { name: "Georgia", chinese: "格鲁吉亚" },
    { name: "Germany", chinese: "德国" },
    { name: "Ghana", chinese: "加纳" },
    { name: "Greece", chinese: "希腊" },
    { name: "Grenada", chinese: "格林纳达" },
    { name: "Guatemala", chinese: "危地马拉" },
    { name: "Guinea", chinese: "几内亚" },
    { name: "Guinea-Bissau", chinese: "几内亚比绍" },
    { name: "Guyana", chinese: "圭亚那" },
    { name: "Haiti", chinese: "海地" },
    { name: "Holy See", chinese: "圣座" },
    { name: "Honduras", chinese: "洪都拉斯" },
    { name: "Hungary", chinese: "匈牙利" },
    { name: "Iceland", chinese: "冰岛" },
    { name: "India", chinese: "印度" },
    { name: "Indonesia", chinese: "印度尼西亚" },
    { name: "Iran", chinese: "伊朗" },
    { name: "Iraq", chinese: "伊拉克" },
    { name: "Ireland", chinese: "爱尔兰" },
    { name: "Israel", chinese: "以色列" },
    { name: "Italy", chinese: "意大利" },
    { name: "Jamaica", chinese: "牙买加" },
    { name: "Japan", chinese: "日本" },
    { name: "Jordan", chinese: "约旦" },
    { name: "Kazakhstan", chinese: "哈萨克斯坦" },
    { name: "Kenya", chinese: "肯尼亚" },
    { name: "Kiribati", chinese: "基里巴斯" },
    { name: "Kuwait", chinese: "科威特" },
    { name: "Kyrgyzstan", chinese: "吉尔吉斯斯坦" },
    { name: "Laos", chinese: "老挝" },
    { name: "Latvia", chinese: "拉脱维亚" },
    { name: "Lebanon", chinese: "黎巴嫩" },
    { name: "Lesotho", chinese: "莱索托" },
    { name: "Liberia", chinese: "利比里亚" },
    { name: "Libya", chinese: "利比亚" },
    { name: "Liechtenstein", chinese: "列支敦士登" },
    { name: "Lithuania", chinese: "立陶宛" },
    { name: "Luxembourg", chinese: "卢森堡" },
    { name: "Madagascar", chinese: "马达加斯加" },
    { name: "Malawi", chinese: "马拉维" },
    { name: "Malaysia", chinese: "马来西亚" },
    { name: "Maldives", chinese: "马尔代夫" },
    { name: "Mali", chinese: "马里" },
    { name: "Malta", chinese: "马耳他" },
    { name: "Marshall Islands", chinese: "马绍尔群岛" },
    { name: "Mauritania", chinese: "毛里塔尼亚" },
    { name: "Mauritius", chinese: "毛里求斯" },
    { name: "Mexico", chinese: "墨西哥" },
    { name: "Micronesia", chinese: "密克罗尼西亚" },
    { name: "Moldova", chinese: "摩尔多瓦" },
    { name: "Monaco", chinese: "摩纳哥" },
    { name: "Mongolia", chinese: "蒙古" },
    { name: "Montenegro", chinese: "黑山" },
    { name: "Morocco", chinese: "摩洛哥" },
    { name: "Mozambique", chinese: "莫桑比克" },
    { name: "Myanmar (Burma)", chinese: "缅甸" },
    { name: "Namibia", chinese: "纳米比亚" },
    { name: "Nauru", chinese: "瑙鲁" },
    { name: "Nepal", chinese: "尼泊尔" },
    { name: "Netherlands", chinese: "荷兰" },
    { name: "New Zealand", chinese: "新西兰" },
    { name: "Nicaragua", chinese: "尼加拉瓜" },
    { name: "Niger", chinese: "尼日尔" },
    { name: "Nigeria", chinese: "尼日利亚" },
    { name: "North Korea", chinese: "朝鲜" },
    { name: "North Macedonia", chinese: "北马其顿" },
    { name: "Norway", chinese: "挪威" },
    { name: "Oman", chinese: "阿曼" },
    { name: "Pakistan", chinese: "巴基斯坦" },
    { name: "Palau", chinese: "帕劳" },
    { name: "Palestine State", chinese: "巴勒斯坦" },
    { name: "Panama", chinese: "巴拿马" },
    { name: "Papua New Guinea", chinese: "巴布亚新几内亚" },
    { name: "Paraguay", chinese: "巴拉圭" },
    { name: "Peru", chinese: "秘鲁" },
    { name: "Philippines", chinese: "菲律宾" },
    { name: "Poland", chinese: "波兰" },
    { name: "Portugal", chinese: "葡萄牙" },
    { name: "Qatar", chinese: "卡塔尔" },
    { name: "Romania", chinese: "罗马尼亚" },
    { name: "Russia", chinese: "俄罗斯" },
    { name: "Rwanda", chinese: "卢旺达" },
    { name: "Saint Kitts and Nevis", chinese: "圣基茨和尼维斯" },
    { name: "Saint Lucia", chinese: "圣卢西亚" },
    { name: "Saint Vincent and the Grenadines", chinese: "圣文森特和格林纳丁斯" },
    { name: "Samoa", chinese: "萨摩亚" },
    { name: "San Marino", chinese: "圣马力诺" },
    { name: "Sao Tome and Principe", chinese: "圣多美和普林西比" },
    { name: "Saudi Arabia", chinese: "沙特阿拉伯" },
    { name: "Senegal", chinese: "塞内加尔" },
    { name: "Serbia", chinese: "塞尔维亚" },
    { name: "Seychelles", chinese: "塞舌尔" },
    { name: "Sierra Leone", chinese: "塞拉利昂" },
    { name: "Singapore", chinese: "新加坡" },
    { name: "Slovakia", chinese: "斯洛伐克" },
    { name: "Slovenia", chinese: "斯洛文尼亚" },
    { name: "Solomon Islands", chinese: "所罗门群岛" },
    { name: "Somalia", chinese: "索马里" },
    { name: "South Africa", chinese: "南非" },
    { name: "South Korea", chinese: "韩国" },
    { name: "South Sudan", chinese: "南苏丹" },
    { name: "Spain", chinese: "西班牙" },
    { name: "Sri Lanka", chinese: "斯里兰卡" },
    { name: "Sudan", chinese: "苏丹" },
    { name: "Suriname", chinese: "苏里南" },
    { name: "Sweden", chinese: "瑞典" },
    { name: "Switzerland", chinese: "瑞士" },
    { name: "Syria", chinese: "叙利亚" },
    { name: "Tajikistan", chinese: "塔吉克斯坦" },
    { name: "Tanzania", chinese: "坦桑尼亚" },
    { name: "Thailand", chinese: "泰国" },
    { name: "Timor-Leste", chinese: "东帝汶" },
    { name: "Togo", chinese: "多哥" },
    { name: "Tonga", chinese: "汤加" },
    { name: "Trinidad and Tobago", chinese: "特立尼达和多巴哥" },
    { name: "Tunisia", chinese: "突尼斯" },
    { name: "Turkey", chinese: "土耳其" },
    { name: "Turkmenistan", chinese: "土库曼斯坦" },
    { name: "Tuvalu", chinese: "图瓦卢" },
    { name: "Uganda", chinese: "乌干达" },
    { name: "Ukraine", chinese: "乌克兰" },
    { name: "United Arab Emirates", chinese: "阿联酋" },
    { name: "United Kingdom", chinese: "英国" },
    { name: "United States of America", chinese: "美国" },
    { name: "Uruguay", chinese: "乌拉圭" },
    { name: "Uzbekistan", chinese: "乌兹别克斯坦" },
    { name: "Vanuatu", chinese: "瓦努阿图" },
    { name: "Venezuela", chinese: "委内瑞拉" },
    { name: "Vietnam", chinese: "越南" },
    { name: "Yemen", chinese: "也门" },
    { name: "Zambia", chinese: "赞比亚" },
    { name: "Zimbabwe", chinese: "津巴布韦" }
];

export const NATIONALITIES = COUNTRIES.map(c => ({
    name: `${c.chinese} ${c.name}`,
    value: c.name
}));

export const LANGUAGES = [
    { name: "English", chinese: "英语" },
    { name: "French", chinese: "法语" },
    { name: "Chinese", chinese: "汉语" },
    { name: "Spanish", chinese: "西班牙语" },
    { name: "Arabic", chinese: "阿拉伯语" },
    { name: "Russian", chinese: "俄语" },
    { name: "Portuguese", chinese: "葡萄牙语" },
    { name: "German", chinese: "德语" },
    { name: "Japanese", chinese: "日语" },
    { name: "Korean", chinese: "韩语" },
    { name: "Vietnamese", chinese: "越南语" },
    { name: "Thai", chinese: "泰语" },
    { name: "Italian", chinese: "意大利语" },
    { name: "Dutch", chinese: "荷兰语" },
    { name: "Turkish", chinese: "土耳其语" },
    { name: "Hindi", chinese: "印地语" },
    { name: "Urdu", chinese: "乌尔都语" },
    { name: "Bengali", chinese: "孟加拉语" },
    { name: "Indonesian", chinese: "印尼语" },
    { name: "Malay", chinese: "马来语" },
    { name: "Swahili", chinese: "斯瓦希里语" }
];

export const RELATIONSHIPS = [
    { value: 'None', name: '无 None' },
    { value: 'Father', name: '父亲 Father' },
    { value: 'Mother', name: '母亲 Mother' },
    { value: 'Brother', name: '兄弟 Brother' },
    { value: 'Sister', name: '姐妹 Sister' },
    { value: 'Uncle', name: '叔叔 Uncle' },
    { value: 'Aunt', name: '阿姨 Aunt' },
    { value: 'Other', name: '其他 Other' }
];

export const OCCUPATIONS = [
    { value: 'Worker', name: '工人 Worker' },
    { value: 'Farmer', name: '农民 Farmer' },
    { value: 'Teacher', name: '教师 Teacher' },
    { value: 'Student', name: '学生 Student' },
    { value: 'Manager', name: '经理 Manager' },
    { value: 'Business Owner', name: '店主 Business Owner' },
    { value: 'Doctor', name: '医生 Doctor' },
    { value: 'Other', name: '其他 Other' }
];

export const INDUSTRY_TYPES = [
    { value: 'Education', name: '教育 Education' },
    { value: 'Healthcare', name: '医疗 Healthcare' },
    { value: 'Technology', name: '技术 Technology' },
    { value: 'Agri-Business', name: '农业商务 Agri-Business' },
    { value: 'Manufacturing', name: '制造业 Manufacturing' },
    { value: 'Retail', name: '零售业 Retail' },
    { value: 'Government', name: '政府 Government' },
    { value: 'Other', name: '其他 Other' }
];
